config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  resources :admins

  root 'home#index'
   
  resources :builders 
  get 'builders/index' => 'builders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.fetch(:admin, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:first_name, :last_name, :email, :address, :state, 
           :city, :pincode, :country, :college_name, :aggregate_mark, :college_address, 
            :school_name_10th, :aggregate_mark_10th, :school_10th_address, :school_name_12th, 
            :aggregate_mark_12th, :school_12th_address, :job_title, :company_name, :location, :salary, 
            :salary, :from, :to, :hobbies_interest, :professional_skills, :languages)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeBuilder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>Basic Details</h4>
    <%= form.label :First_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :Last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :address %>
  </div>
  
  <div class="field">
    <%= form.label :State %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :Pincode %>
    <%= form.text_field :pincode %>
  </div>  

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :country %>
  </div>  

  <div class="field">
  <h4>Education</h4>
    <%= form.label :College_name %>
    <%= form.text_field :college_name %>
  </div>

  <div class="field">
    <%= form.label :Aggregate_mark %>
    <%= form.text_field :aggregate_mark %>
  </div>    

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :college_address %>
  </div>

  <div class="field">
    <%= form.label :School_name_10th %>
    <%= form.text_field :school_name_10th %>
  </div>

  <div class="field">
    <%= form.label :Aggregate_marks %>
    <%= form.text_field :aggregate_mark_10th%>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :school_10th_address %>
  </div>

    <div class="field">
     <%= form.label :School_name_12th %>
     <%= form.text_field :school_name_12th %>
    </div>

    <div class="field">
     <%= form.label :Aggregate_marks %>
     <%= form.text_field :aggregate_mark_12th %>
    </div>

    <div class="field">
     <%= form.label :Address %>
     <%= form.text_field :school_12th_address %>
    </div>    

    <div class="field">
    <h4>Expierence</h4>
     <%= form.label :Job_title %>
     <%= form.text_field :job_title %>
    </div>

    <div class="field">
     <%= form.label :Company_name %>
     <%= form.text_field :company_name %>
    </div>

    <div class="field">
     <%= form.label :Location %>
     <%= form.text_field :location%>
    </div>

    <div class="field">
     <%= form.label :Salary %>
     <%= form.text_field :salary %>
    </div> 

    <div class="field">
     <%= form.label :From %>
     <%= form.text_field :from %>
    </div>    

    <div class="field">
     <%= form.label :To %>
     <%= form.text_field :to %>
    </div>    

    <div class="field">
     <%= form.label :Hobbies_interest %>
     <%= form.text_field :hobbies_interest %>
    </div>

    <div class="field">
     <%= form.label :Professional_skills %>
     <%= form.text_field :professional_skills %>
    </div>

    <div class="field">
     <%= form.label :Languages %>
     <%= form.text_field :languages %>
    </div>            

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>First_name</th>
      <th>Last_name</th>
      <th>Email</th>
      <th>Address</th>
      <th>City</th>
      <th>pincode</th>
      <th>Country</th>
      <th>College_name</th>
      <th>Aggregate_mark</th>
      <th>College_address</th>
      <th>School_name_10th</th>
      <th>Aggregate_mark_10th</th>
      <th>School_10th_address</th>
      <th>School_name_12th</th>
      <th>Aggregate_mark_12th</th>
      <th>School_12th_address</th>
      <th>Job_title</th>
      <th>Company_name</th>
      <th>Location</th>
      <th>Salary</th>
      <th>From</th>
      <th>To</th>
      <th>Hobbies_interest</th>
      <th>Professional_skills</th>
      <th>Languages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.first_name %></td>
        <td><%= resume.last_name %></td>
        <td><%= resume.email %></td>
        <td><%= resume.address %></td>
        <td><%= resume.city %></td>
        <td><%= resume.pincode %></td>
        <td><%= resume.country %></td>                
        <td><%= resume.college_name %></td>
        <td><%= resume.aggregate_mark %></td> 
        <td><%= resume.college_address %></td>
        <td><%= resume.school_name_10th %></td> 
        <td><%= resume.aggregate_mark_10th %></td>
        <td><%= resume.school_10th_address%></td>
        <td><%= resume.school_name_12th%></td>
        <td><%= resume.aggregate_mark_12th%></td>
        <td><%= resume.school_12th_address%></td>
        <td><%= resume.job_title%></td>
        <td><%= resume.company_name%></td>
        <td><%= resume.location%></td>
        <td><%= resume.salary%></td>
        <td><%= resume.from%></td>
        <td><%= resume.to%></td> 
        <td><%= resume.hobbies_interest%></td>
        <td><%= resume.professional_skills%></td>
        <td><%= resume.languages%></td>                               
        
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Basic Details</h4>
<p>
  <strong>First name:</strong>
  <%= @resume.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @resume.last_name %>
</p>

<p>
<strong>Email:</strong>
<%= @resume.email%>
</p>

<p>
<strong>Address:</strong>
<%= @resume.address%>
</p>

<p>
<strong>State:</strong>
<%= @resume.state%>
</p>

<p>
<strong>City:</strong>
<%= @resume.city%>
</p>

<p>
<strong>Pincode:</strong>
<%= @resume.pincode%>
</p>

<p>
<strong>Country:</strong>
<%= @resume.country%>
</p>

<h4>Education</h4>
<p>
<strong>College_name:</strong>
<%= @resume.college_name%>
</p>

<p>
<strong>Aggregate_mark:</strong>
<%= @resume.aggregate_mark%>
</p>

<p>
<strong>College_address:</strong>
<%= @resume.college_address%>
</p>

<p>
<strong>School_name_10th:</strong>
<%= @resume.school_name_10th%>
</p>

<p>
<strong>Aggregate_mark_10th:</strong>
<%= @resume.aggregate_mark_10th%>
</p>

<p>
<strong>School_10th_address:</strong>
<%= @resume.school_10th_address%>
</p>

<p>
<strong>School_name_12th:</strong>
<%= @resume.school_name_12th%>
</p>

<p>
<strong>Aggregate_mark_12th:</strong>
<%= @resume.aggregate_mark_12th%>
</p>


<p>
<strong>School_12th_address:</strong>
<%= @resume.school_12th_address%>
</p>


<p>
<strong>Job_title:</strong>
<%= @resume.job_title%>
</p>


<p>
<strong>Company_name:</strong>
<%= @resume.company_name%>
</p>


<p>
<strong>Job_title:</strong>
<%= @resume.job_title%>
</p>

<p>
<strong>Company_name:</strong>
<%= @resume.company_name%>
</p>


<p>
<strong>location:</strong>
<%= @resume.location%>
</p>

<p>
<strong>Salary:</strong>
<%= @resume.salary%>
</p>

<p>
<strong>from:</strong>
<%= @resume.from%>
</p>

<p>
<strong>to:</strong>
<%= @resume.from%>
</p>

<p>
<strong>Hobbies_interest:</strong>
<%= @resume.hobbies_interest%>
</p>

<p>
<strong>Professional_skills:</strong>
<%= @resume.professional_skills%>
</p>

<p>
<strong>languages:</strong>
<%= @resume.languages%>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>